# Generated by Django 6.0.6 on 2026-06-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('official_website_url', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('pool_type', models.CharField(choices=[('outdoor', 'Outdoor'), ('wading', 'Wading'), ('spray', 'Spray'), ('indoor', 'Indoor')], default='outdoor', max_length=20)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('opening_date_source_url', models.URLField(blank=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('closing_date_source_url', models.URLField(blank=True)),
                ('hours', models.CharField(blank=True, help_text='e.g. "11–7 M–F, 12–5 weekends"', max_length=200)),
                ('hours_source_url', models.URLField(blank=True)),
                ('weekday_schedule', models.TextField(blank=True, help_text="One period per line, e.g. '11:00–11:50am: Free swim'")),
                ('weekday_schedule_source_url', models.URLField(blank=True)),
                ('weekend_schedule', models.TextField(blank=True)),
                ('weekend_schedule_source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_changes', to='pools.pool')),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('submitter_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('raw_fetched_content', models.TextField(blank=True)),
                ('llm_response', models.JSONField(blank=True, null=True)),
                ('parsed_opening_date', models.DateField(blank=True, null=True)),
                ('parsed_closing_date', models.DateField(blank=True, null=True)),
                ('parsed_hours', models.CharField(blank=True, max_length=200)),
                ('parsed_weekday_schedule', models.TextField(blank=True)),
                ('parsed_weekend_schedule', models.TextField(blank=True)),
                ('parsed_notes', models.TextField(blank=True)),
                ('llm_confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_notes', models.TextField(blank=True)),
                ('parsed_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='pools.pool')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
