# Generated by Django 6.0.6 on 2026-06-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='ppr_amenity_id',
            field=models.CharField(blank=True, help_text='Stable ID from OpenDataPhilly; used for idempotent imports', max_length=50, unique=True),
        ),
    ]
