# Generated by Django 6.0.6 on 2026-06-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_add_ppr_amenity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='uploaded_image',
            field=models.FileField(blank=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
