# Generated by Django 6.0.6 on 2026-06-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_add_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='updates',
            field=models.TextField(blank=True, help_text='Current-season updates from submissions or announcements'),
        ),
        migrations.AddField(
            model_name='pool',
            name='updates_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='notes',
            field=models.TextField(blank=True, help_text='Permanent info about this pool (facilities, accessibility, etc.)'),
        ),
    ]
