# Generated by Django 6.0.6 on 2026-06-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_add_pool_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='social_media_url',
            field=models.URLField(blank=True, help_text='Instagram, Facebook, etc.'),
        ),
    ]
