# Generated by Django 6.0.6 on 2026-06-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_add_pool_social_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='hours_source_url',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='parsed_hours',
        ),
    ]
