# Generated by Django 6.0.6 on 2026-06-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0010_add_pool_alternate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Used only for abuse-rate limiting', null=True)),
                ('year', models.IntegerField(help_text='Season year this like was cast in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pools.pool')),
            ],
            options={
                'unique_together': {('pool', 'voter_id', 'year')},
            },
        ),
    ]
