# Generated by Django 6.0.6 on 2026-06-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0011_poollike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poolseasonhistory',
            options={'ordering': ['year'], 'verbose_name_plural': 'pool season histories'},
        ),
    ]
