# Generated by Django 6.0.6 on 2026-06-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0012_fix_season_history_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolseasonhistory',
            name='weekday_schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poolseasonhistory',
            name='weekend_schedule',
            field=models.TextField(blank=True),
        ),
    ]
