# Generated by Django 6.0.6 on 2026-06-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0015_add_pool_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hold', 'Hold'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
