# Generated by Django 6.0.6 on 2026-06-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0016_add_submission_hold_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatHealthEmergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, help_text='Blank while still in effect / not yet confirmed ended.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Heat health emergencies',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='HeatEmergencyPressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(unique=True)),
                ('raw_content', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, help_text='Date the press release itself was published.', null=True)),
                ('is_active_emergency', models.BooleanField(default=True, help_text='False if this release announces the emergency ending')),
                ('parsed_starts_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_ends_at', models.DateTimeField(blank=True, null=True)),
                ('llm_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('emergency', models.ForeignKey(blank=True, help_text='Which emergency this release acts on (a revision or an end). Leave blank to start a brand-new emergency when applied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_releases', to='pools.heathealthemergency')),
            ],
            options={
                'ordering': ['-published_at', '-detected_at'],
            },
        ),
    ]
