# Generated by Django 6.0.6 on 2026-06-30 21:17

from django.db import migrations, models


def populate_release_kind(apps, schema_editor):
    HeatEmergencyPressRelease = apps.get_model('pools', 'HeatEmergencyPressRelease')
    HeatEmergencyPressRelease.objects.filter(is_active_emergency=True).update(release_kind='declares_or_extends')
    HeatEmergencyPressRelease.objects.filter(is_active_emergency=False).update(release_kind='ends')


def reverse_release_kind(apps, schema_editor):
    HeatEmergencyPressRelease = apps.get_model('pools', 'HeatEmergencyPressRelease')
    HeatEmergencyPressRelease.objects.filter(release_kind='declares_or_extends').update(is_active_emergency=True)
    HeatEmergencyPressRelease.objects.filter(release_kind='ends').update(is_active_emergency=False)


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0017_heathealthemergency_heatemergencypressrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatemergencypressrelease',
            name='release_kind',
            field=models.CharField(choices=[('declares_or_extends', 'Declares / extends'), ('ends', 'Ends')], default='declares_or_extends', help_text='What this specific release announces — not whether an emergency is currently in effect.', max_length=20),
        ),
        migrations.RunPython(populate_release_kind, reverse_release_kind),
        migrations.RemoveField(
            model_name='heatemergencypressrelease',
            name='is_active_emergency',
        ),
    ]
