# Generated by Django 6.0.6 on 2026-07-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0018_remove_heatemergencypressrelease_is_active_emergency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digest_sent_at', models.DateTimeField(blank=True, help_text="Pending items created after this are 'new' in the next digest.", null=True)),
                ('last_error_email_sent_at', models.DateTimeField(blank=True, help_text='Scraper errors alone trigger at most one email per day.', null=True)),
            ],
        ),
    ]
