# Generated by Django 6.0.6 on 2026-07-10 12:59

from django.db import migrations, models

# The URL previously hardcoded in check_heat_emergency; seeded here so the switch
# to admin-managed heat pages is behavior-neutral with no manual step.
_DPH_URL = 'https://www.phila.gov/departments/department-of-public-health/'


def seed_heat_page(apps, schema_editor):
    MonitoredPage = apps.get_model('pools', 'MonitoredPage')
    page, created = MonitoredPage.objects.get_or_create(
        url=_DPH_URL, defaults={'page_type': 'heat_emergency'},
    )
    if not created and page.page_type != 'heat_emergency':
        page.page_type = 'heat_emergency'
        page.save(update_fields=['page_type'])


def unseed_heat_page(apps, schema_editor):
    MonitoredPage = apps.get_model('pools', 'MonitoredPage')
    MonitoredPage.objects.filter(url=_DPH_URL, page_type='heat_emergency').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0019_digeststate'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredpage',
            name='page_type',
            field=models.CharField(choices=[('pool_info', 'Pool info'), ('heat_emergency', 'Heat emergency info')], default='pool_info', max_length=20),
        ),
        migrations.RunPython(seed_heat_page, unseed_heat_page),
    ]
