# Generated by Django 6.0.6 on 2026-07-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0020_monitoredpage_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulechange',
            name='date_to',
            field=models.DateField(blank=True, help_text='Leave blank for an open-ended change with no known end date', null=True),
        ),
    ]
