# Generated by Django 6.0.6 on 2026-07-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0022_siteannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteannouncement',
            name='color',
            field=models.CharField(choices=[('cyan', 'Cyan'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteannouncement',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank to keep showing indefinitely.', null=True),
        ),
    ]
