# Generated by Django 6.0.6 on 2026-07-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0023_siteannouncement_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteannouncement',
            name='show_on_detail_pages',
            field=models.BooleanField(default=True, help_text='Also show on individual pool detail pages (always shown on the main page).'),
        ),
        migrations.AlterField(
            model_name='siteannouncement',
            name='message',
            field=models.TextField(help_text='Shown in the banner on every page. Markdown links and bold/italic/code are supported; other HTML is stripped.'),
        ),
    ]
