# Generated by Django 6.0.6 on 2026-07-17 21:15

from django.db import migrations
from django.utils import timezone

# Replaces the hardcoded "Schedule info here is crowd-sourced" banner (removed from
# index.html in this same change) with an equivalent admin-managed announcement, so
# the message doesn't just disappear from the live site on deploy.
_MESSAGE = (
    "Schedule info here is crowd-sourced: It's only as current as what people share. "
    "Have updated info? [Submit an update.](/submit/)"
)


def seed_announcement(apps, schema_editor):
    SiteAnnouncement = apps.get_model('pools', 'SiteAnnouncement')
    SiteAnnouncement.objects.get_or_create(
        message=_MESSAGE,
        defaults={
            'color': 'cyan',
            'show_on_detail_pages': False,
            'starts_at': timezone.now(),
            'ends_at': None,
        },
    )


def unseed_announcement(apps, schema_editor):
    SiteAnnouncement = apps.get_model('pools', 'SiteAnnouncement')
    SiteAnnouncement.objects.filter(message=_MESSAGE, color='cyan').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0024_siteannouncement_show_on_detail_pages_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_announcement, unseed_announcement),
    ]
