# Generated by Django 6.0.6 on 2026-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0025_seed_crowd_source_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('salt', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('metric', models.CharField(help_text="e.g. 'visitors', 'pool_view', 'status_filter', 'zip'", max_length=32)),
                ('key', models.CharField(blank=True, help_text='The specific pool slug, filter value, zip, etc.', max_length=100)),
                ('events', models.IntegerField(default=0, help_text='Number of interactions')),
                ('visitors', models.IntegerField(default=0, help_text='Number of distinct visitors that day')),
            ],
            options={
                'ordering': ['-day', 'metric', '-visitors'],
                'unique_together': {('day', 'metric', 'key')},
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(db_index=True, help_text='Local date, so grouping needs no timezone math')),
                ('event', models.CharField(choices=[('index', 'Main page'), ('pool_view', 'Pool detail page'), ('filter', 'Filter / search (JSON fetch)'), ('map_pick', 'Neighborhood picked on map'), ('pin_click', 'Map pin clicked'), ('submit_view', 'Submit form viewed'), ('submit_done', 'Submission completed'), ('other', 'Other page')], db_index=True, max_length=20)),
                ('key', models.CharField(blank=True, help_text='Pool slug for pool views and pin clicks', max_length=100)),
                ('status_filter', models.CharField(blank=True, max_length=20)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('zip_searched', models.CharField(blank=True, max_length=5)),
                ('visitor', models.CharField(db_index=True, help_text='Daily-rotating pseudonym; not linkable across days', max_length=16)),
                ('client_class', models.CharField(default='unknown', help_text="'bot' or 'unknown' — never a positive 'human' claim", max_length=10)),
                ('device', models.CharField(blank=True, max_length=10)),
                ('referrer_host', models.CharField(blank=True, help_text='Host only, and only for external referrers', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['day', 'event'], name='pools_usage_day_ff40b2_idx')],
            },
        ),
    ]
