# Generated by Django 6.0.6 on 2026-07-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0026_visitorsalt_usagedaily_usageevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='client_class',
            field=models.CharField(default='unknown', help_text="'bot', 'staff' or 'unknown' — never a positive 'human' claim", max_length=10),
        ),
    ]
