# Generated by Django 6.0.6 on 2026-07-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0027_alter_usageevent_client_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRollupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
