# Generated by Django 6.0.6 on 2026-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0028_usagerollupstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='event',
            field=models.CharField(choices=[('index', 'Main page'), ('pool_view', 'Pool detail page'), ('filter', 'Filter / search (JSON fetch)'), ('map_pick', 'Neighborhood picked on map'), ('pin_click', 'Map pin clicked'), ('pageview_js', 'Page loaded (browser confirmed)'), ('submit_view', 'Submit form viewed'), ('submit_done', 'Submission completed'), ('other', 'Other page')], db_index=True, max_length=20),
        ),
    ]
