# Generated by Django 6.0.6 on 2026-07-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0030_alter_usageevent_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usagedaily',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usagedaily',
            name='audience',
            field=models.CharField(default='human', help_text="Who was counted: 'human' is every visitor the crawler check let through, 'confirmed' only those whose browser ran the page's JavaScript", max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='usagedaily',
            unique_together={('day', 'metric', 'key', 'audience')},
        ),
    ]
