# Generated by Django 6.0.6 on 2026-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0031_alter_usagedaily_unique_together_usagedaily_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='ua_family',
            field=models.CharField(blank=True, help_text="What the user-agent claimed to be, e.g. 'chrome/129' — the claim, not the verdict, and never the string itself", max_length=20),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='event',
            field=models.CharField(choices=[('index', 'Main page'), ('pool_view', 'Pool detail page'), ('filter', 'Filter / search (JSON fetch)'), ('map_pick', 'Neighborhood picked on map'), ('pin_click', 'Map pin clicked'), ('card_click', 'Pool clicked in the list'), ('pageview_js', 'Page loaded (browser confirmed)'), ('submit_view', 'Submit form viewed'), ('submit_done', 'Submission completed'), ('probe', 'Scanner probe (404)'), ('other', 'Other page')], db_index=True, max_length=20),
        ),
    ]
