# Generated by Django 6.0.6 on 2026-07-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0032_usageevent_ua_family_alter_usageevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='datacenter',
            field=models.BooleanField(default=False, help_text="Whether the request came from a hosting provider's address range. The address itself is read once and never stored"),
        ),
    ]
