# Generated by Django 6.0.6 on 2026-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0033_usageevent_datacenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='event',
            field=models.CharField(choices=[('index', 'Main page'), ('pool_view', 'Pool detail page'), ('filter', 'Filter / search (JSON fetch)'), ('map_pick', 'Neighborhood picked on map'), ('pin_click', 'Map pin clicked'), ('card_click', 'Pool clicked in the list'), ('pageview_js', 'Page loaded (browser confirmed)'), ('submit_view', 'Submit form viewed'), ('submit_done', 'Submission completed'), ('probe', 'Scanner probe (404)'), ('legacy_id', 'Reached a pool by its retired numeric ID, with no referrer'), ('other', 'Other page')], db_index=True, max_length=20),
        ),
    ]
