# Generated by Django 6.0.6 on 2026-07-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0034_alter_usageevent_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('visitor', models.CharField(max_length=16)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'visitor'), name='unique_submission_throttle_day_visitor')],
            },
        ),
    ]
