# Generated by Django 6.0.6 on 2026-08-20 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0036_alter_usageevent_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolGisState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gis_status', models.CharField(blank=True, help_text='pool_status as last seen in GIS', max_length=30)),
                ('gis_opening_date', models.DateField(blank=True, help_text='pool_open_date as last seen in GIS', null=True)),
                ('gis_closing_date', models.DateField(blank=True, help_text='Unused until the city adds a closing-date field', null=True)),
                ('proposed_opening_date', models.DateField(blank=True, help_text='Last opening date proposed to review from GIS. Suppresses repeat proposals of the same value.', null=True)),
                ('proposed_closing_date', models.DateField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_changed', models.DateTimeField(blank=True, help_text='When a GIS value for this pool last differed from the previous check', null=True)),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gis_state', to='pools.pool')),
            ],
            options={
                'verbose_name': 'pool GIS state',
                'verbose_name_plural': 'pool GIS state',
            },
        ),
    ]
