# Generated by Django 6.0.6 on 2026-08-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0037_poolgisstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='has_ada_lift',
            field=models.BooleanField(default=False, help_text="Pool has a wheelchair lift. From the city's ada_lift field; only an explicit 'Y' counts, so blank and unpopulated are treated the same as 'N'.", verbose_name='Has ADA lift'),
        ),
    ]
