# Generated by Django 6.0.6 on 2026-08-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0038_pool_has_ada_lift'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='ada_lift_filter',
            field=models.CharField(blank=True, help_text="'1' when the ADA-lift checkbox was on; blank when it wasn't, so the rollup's skip-blanks rule counts only the visitors who used it", max_length=4),
        ),
    ]
