# Generated by Django 6.0.6 on 2026-08-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0040_ada_lift_three_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisCheckState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive_fetch_failures', models.PositiveIntegerField(default=0, help_text='Reset to 0 by the first successful fetch.')),
                ('first_failure_at', models.DateTimeField(blank=True, help_text='Start of the current failure streak.', null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'GIS check state',
                'verbose_name_plural': 'GIS check state',
            },
        ),
    ]
