# Generated by Django 6.0.6 on 2026-08-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0041_gischeckstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredpage',
            name='etag',
            field=models.CharField(blank=True, help_text='ETag from the last full response', max_length=256),
        ),
        migrations.AddField(
            model_name='monitoredpage',
            name='extractor_version',
            field=models.PositiveSmallIntegerField(default=0, help_text="Which version of the parser produced content_hash. A mismatch forces a full fetch, since the page can be unchanged while what we read out of it isn't."),
        ),
        migrations.AddField(
            model_name='monitoredpage',
            name='last_full_fetch',
            field=models.DateTimeField(blank=True, help_text='When we last saw a real body. Only a 200 advances this — a 304 must not, or the every-23-hours forced refetch would never come due.', null=True),
        ),
        migrations.AddField(
            model_name='monitoredpage',
            name='last_modified',
            field=models.CharField(blank=True, help_text='Last-Modified header from the last full response, verbatim', max_length=64),
        ),
    ]
