[build]
buildCommand = "python manage.py check_deploy && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn phillypools.wsgi --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/"
healthcheckTimeout = 30

[url-watcher.build]
buildCommand = "echo ok"

[url-watcher.deploy]
startCommand = "python manage.py check_pool_schedule"
